first functional menu
Gathaspar66/Big-Bumper-Bash pull request #2
Opened 2023-08-18 21:44 UTC by hawciu

general working menu flow

2023-08-19 17:30 UTC, Gathaspar66 commented on Big-Bumper-Bash/Assets/UI/MapChoiceScript.cs
> +    public void PressMap1()
In my opinion these 2 methods do exactly the same thing, shouldn't there be one method but with a parameter, what do you think?

2023-08-20 22:50 UTC, Gathaspar66 approved these changes
lgtm!

2023-08-21 20:21 UTC, masslany requested changes

2023-08-21 20:21 UTC, masslany commented on Big-Bumper-Bash/Assets/UI/CarChoiceScript.cs
> +        print("starting game - car choice: " + car);
Unnecessary log

2023-08-21 20:21 UTC, masslany commented on Big-Bumper-Bash/Assets/UI/MapChoiceScript.cs
> +        print("map choice: " + map);
Unnecessary log

2023-08-21 20:21 UTC, masslany commented on Big-Bumper-Bash/Assets/UI/MapChoiceScript.cs
> +    public void PressMap(string map = "no map chosen")
If there is a determined number of maps it'd be better to use enum to represent them.

2023-08-21 20:21 UTC, masslany commented on Big-Bumper-Bash/Assets/UI/CarChoiceScript.cs
> +        //gameObject.SetActive(false);
Don't leave commented out code

2023-08-21 20:21 UTC, masslany commented on Big-Bumper-Bash/Assets/UI/CarChoiceScript.cs
> +    public void PressCar(string car = "no car chosen")
This method certainly doesn't press a car. Correct me if I'm mistaken but they're called when a button is pressed. If that's the case then a better naming convention for them is `OnXyzPressed`. This applies to all the methods across the different screen. Also if the cars are in a determined set, it's better to represent them using an enum.
```suggestion
    public void OnChooseCarButtonPressed(string car = "no car chosen")
```

2023-08-23 20:11 UTC, masslany approved these changes

2023-08-25 16:14 UTC, klaudix30 approved these changes

2023-08-25 16:40 UTC, Gathaspar66 approved these changes
lgtm!

2023-08-25 16:42 UTC, merged